networks:
  default: snapshot
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.3.0
  - Uniswap/v2-core@1.0.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.3.0"
      - "@Uniswap/v2-core=Uniswap/v2-core@1.0.0"
